version: '3.9'
services:
  localstack:
    container_name: localstack
    environment:
      DEBUG: 1
      DOCKER_HOST: unix:///var/run/docker.sock
    image: localstack/localstack:1.4
    ports:
      - '4566:4566'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/health']
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
