on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - run: |
          npm install
          npx prettier --check .
          npx tsc --noEmit
          npm run test
        name: Checks

      - run: npm ci
        name: Clear dependencies

      - run: npm publish
        name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
