on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    services:
      localstack:
        env:
          DEBUG: 1
          DOCKER_HOST: unix:///var/run/docker.sock
        image: localstack/localstack:1.4
        ports:
          - '4566:4566'
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - run: |
          npm install
          npx prettier --check .
          npx tsc --noEmit
          npx jest .
        name: Checks

      - run: npm ci
        name: Clear dependencies

      - run: npm publish
        name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
